/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/camera.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rovercom/outputs/camera.pb-c.h"
void   protobuf_msgs__camera_sensor_output__init
                     (ProtobufMsgs__CameraSensorOutput         *message)
{
  static const ProtobufMsgs__CameraSensorOutput init_value = PROTOBUF_MSGS__CAMERA_SENSOR_OUTPUT__INIT;
  *message = init_value;
}
size_t protobuf_msgs__camera_sensor_output__get_packed_size
                     (const ProtobufMsgs__CameraSensorOutput *message)
{
  assert(message->base.descriptor == &protobuf_msgs__camera_sensor_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__camera_sensor_output__pack
                     (const ProtobufMsgs__CameraSensorOutput *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__camera_sensor_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__camera_sensor_output__pack_to_buffer
                     (const ProtobufMsgs__CameraSensorOutput *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__camera_sensor_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__CameraSensorOutput *
       protobuf_msgs__camera_sensor_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__CameraSensorOutput *)
     protobuf_c_message_unpack (&protobuf_msgs__camera_sensor_output__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__camera_sensor_output__free_unpacked
                     (ProtobufMsgs__CameraSensorOutput *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__camera_sensor_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__resolution__init
                     (ProtobufMsgs__Resolution         *message)
{
  static const ProtobufMsgs__Resolution init_value = PROTOBUF_MSGS__RESOLUTION__INIT;
  *message = init_value;
}
size_t protobuf_msgs__resolution__get_packed_size
                     (const ProtobufMsgs__Resolution *message)
{
  assert(message->base.descriptor == &protobuf_msgs__resolution__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__resolution__pack
                     (const ProtobufMsgs__Resolution *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__resolution__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__resolution__pack_to_buffer
                     (const ProtobufMsgs__Resolution *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__resolution__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__Resolution *
       protobuf_msgs__resolution__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__Resolution *)
     protobuf_c_message_unpack (&protobuf_msgs__resolution__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__resolution__free_unpacked
                     (ProtobufMsgs__Resolution *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__resolution__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__horizontal_scan__init
                     (ProtobufMsgs__HorizontalScan         *message)
{
  static const ProtobufMsgs__HorizontalScan init_value = PROTOBUF_MSGS__HORIZONTAL_SCAN__INIT;
  *message = init_value;
}
size_t protobuf_msgs__horizontal_scan__get_packed_size
                     (const ProtobufMsgs__HorizontalScan *message)
{
  assert(message->base.descriptor == &protobuf_msgs__horizontal_scan__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__horizontal_scan__pack
                     (const ProtobufMsgs__HorizontalScan *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__horizontal_scan__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__horizontal_scan__pack_to_buffer
                     (const ProtobufMsgs__HorizontalScan *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__horizontal_scan__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__HorizontalScan *
       protobuf_msgs__horizontal_scan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__HorizontalScan *)
     protobuf_c_message_unpack (&protobuf_msgs__horizontal_scan__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__horizontal_scan__free_unpacked
                     (ProtobufMsgs__HorizontalScan *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__horizontal_scan__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__debug_frame__init
                     (ProtobufMsgs__DebugFrame         *message)
{
  static const ProtobufMsgs__DebugFrame init_value = PROTOBUF_MSGS__DEBUG_FRAME__INIT;
  *message = init_value;
}
size_t protobuf_msgs__debug_frame__get_packed_size
                     (const ProtobufMsgs__DebugFrame *message)
{
  assert(message->base.descriptor == &protobuf_msgs__debug_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__debug_frame__pack
                     (const ProtobufMsgs__DebugFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__debug_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__debug_frame__pack_to_buffer
                     (const ProtobufMsgs__DebugFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__debug_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__DebugFrame *
       protobuf_msgs__debug_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__DebugFrame *)
     protobuf_c_message_unpack (&protobuf_msgs__debug_frame__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__debug_frame__free_unpacked
                     (ProtobufMsgs__DebugFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__debug_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__canvas_object__point__init
                     (ProtobufMsgs__CanvasObject__Point         *message)
{
  static const ProtobufMsgs__CanvasObject__Point init_value = PROTOBUF_MSGS__CANVAS_OBJECT__POINT__INIT;
  *message = init_value;
}
void   protobuf_msgs__canvas_object__circle__init
                     (ProtobufMsgs__CanvasObject__Circle         *message)
{
  static const ProtobufMsgs__CanvasObject__Circle init_value = PROTOBUF_MSGS__CANVAS_OBJECT__CIRCLE__INIT;
  *message = init_value;
}
void   protobuf_msgs__canvas_object__init
                     (ProtobufMsgs__CanvasObject         *message)
{
  static const ProtobufMsgs__CanvasObject init_value = PROTOBUF_MSGS__CANVAS_OBJECT__INIT;
  *message = init_value;
}
size_t protobuf_msgs__canvas_object__get_packed_size
                     (const ProtobufMsgs__CanvasObject *message)
{
  assert(message->base.descriptor == &protobuf_msgs__canvas_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__canvas_object__pack
                     (const ProtobufMsgs__CanvasObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__canvas_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__canvas_object__pack_to_buffer
                     (const ProtobufMsgs__CanvasObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__canvas_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__CanvasObject *
       protobuf_msgs__canvas_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__CanvasObject *)
     protobuf_c_message_unpack (&protobuf_msgs__canvas_object__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__canvas_object__free_unpacked
                     (ProtobufMsgs__CanvasObject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__canvas_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__canvas__init
                     (ProtobufMsgs__Canvas         *message)
{
  static const ProtobufMsgs__Canvas init_value = PROTOBUF_MSGS__CANVAS__INIT;
  *message = init_value;
}
size_t protobuf_msgs__canvas__get_packed_size
                     (const ProtobufMsgs__Canvas *message)
{
  assert(message->base.descriptor == &protobuf_msgs__canvas__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__canvas__pack
                     (const ProtobufMsgs__Canvas *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__canvas__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__canvas__pack_to_buffer
                     (const ProtobufMsgs__Canvas *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__canvas__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__Canvas *
       protobuf_msgs__canvas__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__Canvas *)
     protobuf_c_message_unpack (&protobuf_msgs__canvas__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__canvas__free_unpacked
                     (ProtobufMsgs__Canvas *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__canvas__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protobuf_msgs__camera_sensor_output__field_descriptors[4] =
{
  {
    "resolution",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__CameraSensorOutput, resolution),
    &protobuf_msgs__resolution__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "horizontalScans",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtobufMsgs__CameraSensorOutput, n_horizontalscans),
    offsetof(ProtobufMsgs__CameraSensorOutput, horizontalscans),
    &protobuf_msgs__horizontal_scan__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detectedObjects",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ProtobufMsgs__CameraSensorOutput, n_detectedobjects),
    offsetof(ProtobufMsgs__CameraSensorOutput, detectedobjects),
    &protobuf_msgs__detected_objects__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "debugFrame",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__CameraSensorOutput, debugframe),
    &protobuf_msgs__debug_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__camera_sensor_output__field_indices_by_name[] = {
  3,   /* field[3] = debugFrame */
  2,   /* field[2] = detectedObjects */
  1,   /* field[1] = horizontalScans */
  0,   /* field[0] = resolution */
};
static const ProtobufCIntRange protobuf_msgs__camera_sensor_output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protobuf_msgs__camera_sensor_output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.CameraSensorOutput",
  "CameraSensorOutput",
  "ProtobufMsgs__CameraSensorOutput",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__CameraSensorOutput),
  4,
  protobuf_msgs__camera_sensor_output__field_descriptors,
  protobuf_msgs__camera_sensor_output__field_indices_by_name,
  1,  protobuf_msgs__camera_sensor_output__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__camera_sensor_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__resolution__field_descriptors[2] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__Resolution, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__Resolution, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__resolution__field_indices_by_name[] = {
  1,   /* field[1] = height */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange protobuf_msgs__resolution__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__resolution__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.Resolution",
  "Resolution",
  "ProtobufMsgs__Resolution",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__Resolution),
  2,
  protobuf_msgs__resolution__field_descriptors,
  protobuf_msgs__resolution__field_indices_by_name,
  1,  protobuf_msgs__resolution__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__resolution__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__horizontal_scan__field_descriptors[3] =
{
  {
    "xLeft",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__HorizontalScan, xleft),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xRight",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__HorizontalScan, xright),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__HorizontalScan, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__horizontal_scan__field_indices_by_name[] = {
  0,   /* field[0] = xLeft */
  1,   /* field[1] = xRight */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange protobuf_msgs__horizontal_scan__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protobuf_msgs__horizontal_scan__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.HorizontalScan",
  "HorizontalScan",
  "ProtobufMsgs__HorizontalScan",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__HorizontalScan),
  3,
  protobuf_msgs__horizontal_scan__field_descriptors,
  protobuf_msgs__horizontal_scan__field_indices_by_name,
  1,  protobuf_msgs__horizontal_scan__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__horizontal_scan__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__debug_frame__field_descriptors[2] =
{
  {
    "jpeg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__DebugFrame, jpeg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canvas",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__DebugFrame, canvas),
    &protobuf_msgs__canvas__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__debug_frame__field_indices_by_name[] = {
  1,   /* field[1] = canvas */
  0,   /* field[0] = jpeg */
};
static const ProtobufCIntRange protobuf_msgs__debug_frame__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__debug_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.DebugFrame",
  "DebugFrame",
  "ProtobufMsgs__DebugFrame",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__DebugFrame),
  2,
  protobuf_msgs__debug_frame__field_descriptors,
  protobuf_msgs__debug_frame__field_indices_by_name,
  2,  protobuf_msgs__debug_frame__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__debug_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__canvas_object__point__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__CanvasObject__Point, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__CanvasObject__Point, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__canvas_object__point__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange protobuf_msgs__canvas_object__point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__canvas_object__point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.CanvasObject.Point",
  "Point",
  "ProtobufMsgs__CanvasObject__Point",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__CanvasObject__Point),
  2,
  protobuf_msgs__canvas_object__point__field_descriptors,
  protobuf_msgs__canvas_object__point__field_indices_by_name,
  1,  protobuf_msgs__canvas_object__point__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__canvas_object__point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__canvas_object__circle__field_descriptors[3] =
{
  {
    "center",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__CanvasObject__Circle, center),
    &protobuf_msgs__canvas_object__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radius",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__CanvasObject__Circle, radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__CanvasObject__Circle, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__canvas_object__circle__field_indices_by_name[] = {
  0,   /* field[0] = center */
  1,   /* field[1] = radius */
  2,   /* field[2] = width */
};
static const ProtobufCIntRange protobuf_msgs__canvas_object__circle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protobuf_msgs__canvas_object__circle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.CanvasObject.Circle",
  "Circle",
  "ProtobufMsgs__CanvasObject__Circle",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__CanvasObject__Circle),
  3,
  protobuf_msgs__canvas_object__circle__field_descriptors,
  protobuf_msgs__canvas_object__circle__field_indices_by_name,
  1,  protobuf_msgs__canvas_object__circle__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__canvas_object__circle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__canvas_object__field_descriptors[1] =
{
  {
    "circle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtobufMsgs__CanvasObject, object_case),
    offsetof(ProtobufMsgs__CanvasObject, circle),
    &protobuf_msgs__canvas_object__circle__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__canvas_object__field_indices_by_name[] = {
  0,   /* field[0] = circle */
};
static const ProtobufCIntRange protobuf_msgs__canvas_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protobuf_msgs__canvas_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.CanvasObject",
  "CanvasObject",
  "ProtobufMsgs__CanvasObject",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__CanvasObject),
  1,
  protobuf_msgs__canvas_object__field_descriptors,
  protobuf_msgs__canvas_object__field_indices_by_name,
  1,  protobuf_msgs__canvas_object__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__canvas_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__canvas__field_descriptors[3] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__Canvas, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__Canvas, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "objects",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtobufMsgs__Canvas, n_objects),
    offsetof(ProtobufMsgs__Canvas, objects),
    &protobuf_msgs__canvas_object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__canvas__field_indices_by_name[] = {
  1,   /* field[1] = height */
  2,   /* field[2] = objects */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange protobuf_msgs__canvas__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protobuf_msgs__canvas__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.Canvas",
  "Canvas",
  "ProtobufMsgs__Canvas",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__Canvas),
  3,
  protobuf_msgs__canvas__field_descriptors,
  protobuf_msgs__canvas__field_indices_by_name,
  1,  protobuf_msgs__canvas__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__canvas__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue protobuf_msgs__detected_objects__enum_values_by_number[10] =
{
  { "FINISH_LINE", "PROTOBUF_MSGS__DETECTED_OBJECTS__FINISH_LINE", 0 },
  { "OFF_TRACK", "PROTOBUF_MSGS__DETECTED_OBJECTS__OFF_TRACK", 1 },
  { "OBSTACLE", "PROTOBUF_MSGS__DETECTED_OBJECTS__OBSTACLE", 2 },
  { "INTERSECTION", "PROTOBUF_MSGS__DETECTED_OBJECTS__INTERSECTION", 3 },
  { "MISSING_LEFT_LANE", "PROTOBUF_MSGS__DETECTED_OBJECTS__MISSING_LEFT_LANE", 4 },
  { "MISSING_RIGHT_LANE", "PROTOBUF_MSGS__DETECTED_OBJECTS__MISSING_RIGHT_LANE", 5 },
  { "SHARP_RIGHT", "PROTOBUF_MSGS__DETECTED_OBJECTS__SHARP_RIGHT", 6 },
  { "SHARP_LEFT", "PROTOBUF_MSGS__DETECTED_OBJECTS__SHARP_LEFT", 7 },
  { "U_TURN", "PROTOBUF_MSGS__DETECTED_OBJECTS__U_TURN", 8 },
  { "S_TURN", "PROTOBUF_MSGS__DETECTED_OBJECTS__S_TURN", 9 },
};
static const ProtobufCIntRange protobuf_msgs__detected_objects__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex protobuf_msgs__detected_objects__enum_values_by_name[10] =
{
  { "FINISH_LINE", 0 },
  { "INTERSECTION", 3 },
  { "MISSING_LEFT_LANE", 4 },
  { "MISSING_RIGHT_LANE", 5 },
  { "OBSTACLE", 2 },
  { "OFF_TRACK", 1 },
  { "SHARP_LEFT", 7 },
  { "SHARP_RIGHT", 6 },
  { "S_TURN", 9 },
  { "U_TURN", 8 },
};
const ProtobufCEnumDescriptor protobuf_msgs__detected_objects__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "protobuf_msgs.DetectedObjects",
  "DetectedObjects",
  "ProtobufMsgs__DetectedObjects",
  "protobuf_msgs",
  10,
  protobuf_msgs__detected_objects__enum_values_by_number,
  10,
  protobuf_msgs__detected_objects__enum_values_by_name,
  1,
  protobuf_msgs__detected_objects__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
