/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/generic.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rovercom/outputs/generic.pb-c.h"
void   protobuf_msgs__generic_int_scalar__init
                     (ProtobufMsgs__GenericIntScalar         *message)
{
  static const ProtobufMsgs__GenericIntScalar init_value = PROTOBUF_MSGS__GENERIC_INT_SCALAR__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_int_scalar__get_packed_size
                     (const ProtobufMsgs__GenericIntScalar *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_int_scalar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_int_scalar__pack
                     (const ProtobufMsgs__GenericIntScalar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_int_scalar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_int_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericIntScalar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_int_scalar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericIntScalar *
       protobuf_msgs__generic_int_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericIntScalar *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_int_scalar__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_int_scalar__free_unpacked
                     (ProtobufMsgs__GenericIntScalar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_int_scalar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__generic_float_scalar__init
                     (ProtobufMsgs__GenericFloatScalar         *message)
{
  static const ProtobufMsgs__GenericFloatScalar init_value = PROTOBUF_MSGS__GENERIC_FLOAT_SCALAR__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_float_scalar__get_packed_size
                     (const ProtobufMsgs__GenericFloatScalar *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_float_scalar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_float_scalar__pack
                     (const ProtobufMsgs__GenericFloatScalar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_float_scalar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_float_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericFloatScalar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_float_scalar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericFloatScalar *
       protobuf_msgs__generic_float_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericFloatScalar *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_float_scalar__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_float_scalar__free_unpacked
                     (ProtobufMsgs__GenericFloatScalar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_float_scalar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__generic_bool_scalar__init
                     (ProtobufMsgs__GenericBoolScalar         *message)
{
  static const ProtobufMsgs__GenericBoolScalar init_value = PROTOBUF_MSGS__GENERIC_BOOL_SCALAR__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_bool_scalar__get_packed_size
                     (const ProtobufMsgs__GenericBoolScalar *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_scalar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_bool_scalar__pack
                     (const ProtobufMsgs__GenericBoolScalar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_scalar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_bool_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericBoolScalar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_scalar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericBoolScalar *
       protobuf_msgs__generic_bool_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericBoolScalar *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_bool_scalar__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_bool_scalar__free_unpacked
                     (ProtobufMsgs__GenericBoolScalar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_scalar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__generic_string_scalar__init
                     (ProtobufMsgs__GenericStringScalar         *message)
{
  static const ProtobufMsgs__GenericStringScalar init_value = PROTOBUF_MSGS__GENERIC_STRING_SCALAR__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_string_scalar__get_packed_size
                     (const ProtobufMsgs__GenericStringScalar *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_string_scalar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_string_scalar__pack
                     (const ProtobufMsgs__GenericStringScalar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_string_scalar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_string_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericStringScalar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_string_scalar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericStringScalar *
       protobuf_msgs__generic_string_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericStringScalar *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_string_scalar__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_string_scalar__free_unpacked
                     (ProtobufMsgs__GenericStringScalar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_string_scalar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__generic_int_array__init
                     (ProtobufMsgs__GenericIntArray         *message)
{
  static const ProtobufMsgs__GenericIntArray init_value = PROTOBUF_MSGS__GENERIC_INT_ARRAY__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_int_array__get_packed_size
                     (const ProtobufMsgs__GenericIntArray *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_int_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_int_array__pack
                     (const ProtobufMsgs__GenericIntArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_int_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_int_array__pack_to_buffer
                     (const ProtobufMsgs__GenericIntArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_int_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericIntArray *
       protobuf_msgs__generic_int_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericIntArray *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_int_array__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_int_array__free_unpacked
                     (ProtobufMsgs__GenericIntArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_int_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__generic_float_array__init
                     (ProtobufMsgs__GenericFloatArray         *message)
{
  static const ProtobufMsgs__GenericFloatArray init_value = PROTOBUF_MSGS__GENERIC_FLOAT_ARRAY__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_float_array__get_packed_size
                     (const ProtobufMsgs__GenericFloatArray *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_float_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_float_array__pack
                     (const ProtobufMsgs__GenericFloatArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_float_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_float_array__pack_to_buffer
                     (const ProtobufMsgs__GenericFloatArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_float_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericFloatArray *
       protobuf_msgs__generic_float_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericFloatArray *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_float_array__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_float_array__free_unpacked
                     (ProtobufMsgs__GenericFloatArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_float_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__generic_bool_array__init
                     (ProtobufMsgs__GenericBoolArray         *message)
{
  static const ProtobufMsgs__GenericBoolArray init_value = PROTOBUF_MSGS__GENERIC_BOOL_ARRAY__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_bool_array__get_packed_size
                     (const ProtobufMsgs__GenericBoolArray *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_bool_array__pack
                     (const ProtobufMsgs__GenericBoolArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_bool_array__pack_to_buffer
                     (const ProtobufMsgs__GenericBoolArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericBoolArray *
       protobuf_msgs__generic_bool_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericBoolArray *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_bool_array__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_bool_array__free_unpacked
                     (ProtobufMsgs__GenericBoolArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_bool_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__generic_string_array__init
                     (ProtobufMsgs__GenericStringArray         *message)
{
  static const ProtobufMsgs__GenericStringArray init_value = PROTOBUF_MSGS__GENERIC_STRING_ARRAY__INIT;
  *message = init_value;
}
size_t protobuf_msgs__generic_string_array__get_packed_size
                     (const ProtobufMsgs__GenericStringArray *message)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_string_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__generic_string_array__pack
                     (const ProtobufMsgs__GenericStringArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_string_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__generic_string_array__pack_to_buffer
                     (const ProtobufMsgs__GenericStringArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__generic_string_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__GenericStringArray *
       protobuf_msgs__generic_string_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__GenericStringArray *)
     protobuf_c_message_unpack (&protobuf_msgs__generic_string_array__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__generic_string_array__free_unpacked
                     (ProtobufMsgs__GenericStringArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__generic_string_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protobuf_msgs__generic_int_scalar__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericIntScalar, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericIntScalar, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_int_scalar__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange protobuf_msgs__generic_int_scalar__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_int_scalar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericIntScalar",
  "GenericIntScalar",
  "ProtobufMsgs__GenericIntScalar",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericIntScalar),
  2,
  protobuf_msgs__generic_int_scalar__field_descriptors,
  protobuf_msgs__generic_int_scalar__field_indices_by_name,
  1,  protobuf_msgs__generic_int_scalar__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_int_scalar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__generic_float_scalar__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericFloatScalar, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericFloatScalar, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_float_scalar__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange protobuf_msgs__generic_float_scalar__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_float_scalar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericFloatScalar",
  "GenericFloatScalar",
  "ProtobufMsgs__GenericFloatScalar",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericFloatScalar),
  2,
  protobuf_msgs__generic_float_scalar__field_descriptors,
  protobuf_msgs__generic_float_scalar__field_indices_by_name,
  1,  protobuf_msgs__generic_float_scalar__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_float_scalar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__generic_bool_scalar__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericBoolScalar, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericBoolScalar, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_bool_scalar__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange protobuf_msgs__generic_bool_scalar__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_bool_scalar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericBoolScalar",
  "GenericBoolScalar",
  "ProtobufMsgs__GenericBoolScalar",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericBoolScalar),
  2,
  protobuf_msgs__generic_bool_scalar__field_descriptors,
  protobuf_msgs__generic_bool_scalar__field_indices_by_name,
  1,  protobuf_msgs__generic_bool_scalar__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_bool_scalar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__generic_string_scalar__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericStringScalar, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericStringScalar, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_string_scalar__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange protobuf_msgs__generic_string_scalar__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_string_scalar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericStringScalar",
  "GenericStringScalar",
  "ProtobufMsgs__GenericStringScalar",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericStringScalar),
  2,
  protobuf_msgs__generic_string_scalar__field_descriptors,
  protobuf_msgs__generic_string_scalar__field_indices_by_name,
  1,  protobuf_msgs__generic_string_scalar__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_string_scalar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__generic_int_array__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericIntArray, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtobufMsgs__GenericIntArray, n_values),
    offsetof(ProtobufMsgs__GenericIntArray, values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_int_array__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange protobuf_msgs__generic_int_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_int_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericIntArray",
  "GenericIntArray",
  "ProtobufMsgs__GenericIntArray",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericIntArray),
  2,
  protobuf_msgs__generic_int_array__field_descriptors,
  protobuf_msgs__generic_int_array__field_indices_by_name,
  1,  protobuf_msgs__generic_int_array__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_int_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__generic_float_array__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericFloatArray, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ProtobufMsgs__GenericFloatArray, n_values),
    offsetof(ProtobufMsgs__GenericFloatArray, values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_float_array__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange protobuf_msgs__generic_float_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_float_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericFloatArray",
  "GenericFloatArray",
  "ProtobufMsgs__GenericFloatArray",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericFloatArray),
  2,
  protobuf_msgs__generic_float_array__field_descriptors,
  protobuf_msgs__generic_float_array__field_indices_by_name,
  1,  protobuf_msgs__generic_float_array__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_float_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__generic_bool_array__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericBoolArray, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ProtobufMsgs__GenericBoolArray, n_values),
    offsetof(ProtobufMsgs__GenericBoolArray, values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_bool_array__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange protobuf_msgs__generic_bool_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_bool_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericBoolArray",
  "GenericBoolArray",
  "ProtobufMsgs__GenericBoolArray",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericBoolArray),
  2,
  protobuf_msgs__generic_bool_array__field_descriptors,
  protobuf_msgs__generic_bool_array__field_indices_by_name,
  1,  protobuf_msgs__generic_bool_array__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_bool_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__generic_string_array__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__GenericStringArray, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ProtobufMsgs__GenericStringArray, n_values),
    offsetof(ProtobufMsgs__GenericStringArray, values),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__generic_string_array__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange protobuf_msgs__generic_string_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__generic_string_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.GenericStringArray",
  "GenericStringArray",
  "ProtobufMsgs__GenericStringArray",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__GenericStringArray),
  2,
  protobuf_msgs__generic_string_array__field_descriptors,
  protobuf_msgs__generic_string_array__field_indices_by_name,
  1,  protobuf_msgs__generic_string_array__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__generic_string_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
