/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/lidar.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rovercom/outputs/lidar.pb-c.h"
void   protobuf_msgs__lidar_sensor_output__scan__init
                     (ProtobufMsgs__LidarSensorOutput__Scan         *message)
{
  static const ProtobufMsgs__LidarSensorOutput__Scan init_value = PROTOBUF_MSGS__LIDAR_SENSOR_OUTPUT__SCAN__INIT;
  *message = init_value;
}
void   protobuf_msgs__lidar_sensor_output__init
                     (ProtobufMsgs__LidarSensorOutput         *message)
{
  static const ProtobufMsgs__LidarSensorOutput init_value = PROTOBUF_MSGS__LIDAR_SENSOR_OUTPUT__INIT;
  *message = init_value;
}
size_t protobuf_msgs__lidar_sensor_output__get_packed_size
                     (const ProtobufMsgs__LidarSensorOutput *message)
{
  assert(message->base.descriptor == &protobuf_msgs__lidar_sensor_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__lidar_sensor_output__pack
                     (const ProtobufMsgs__LidarSensorOutput *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__lidar_sensor_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__lidar_sensor_output__pack_to_buffer
                     (const ProtobufMsgs__LidarSensorOutput *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__lidar_sensor_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__LidarSensorOutput *
       protobuf_msgs__lidar_sensor_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__LidarSensorOutput *)
     protobuf_c_message_unpack (&protobuf_msgs__lidar_sensor_output__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__lidar_sensor_output__free_unpacked
                     (ProtobufMsgs__LidarSensorOutput *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__lidar_sensor_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protobuf_msgs__lidar_sensor_output__scan__field_descriptors[4] =
{
  {
    "angle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__LidarSensorOutput__Scan, angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__LidarSensorOutput__Scan, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__LidarSensorOutput__Scan, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isStart",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__LidarSensorOutput__Scan, isstart),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__lidar_sensor_output__scan__field_indices_by_name[] = {
  0,   /* field[0] = angle */
  1,   /* field[1] = distance */
  3,   /* field[3] = isStart */
  2,   /* field[2] = quality */
};
static const ProtobufCIntRange protobuf_msgs__lidar_sensor_output__scan__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protobuf_msgs__lidar_sensor_output__scan__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.LidarSensorOutput.Scan",
  "Scan",
  "ProtobufMsgs__LidarSensorOutput__Scan",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__LidarSensorOutput__Scan),
  4,
  protobuf_msgs__lidar_sensor_output__scan__field_descriptors,
  protobuf_msgs__lidar_sensor_output__scan__field_indices_by_name,
  1,  protobuf_msgs__lidar_sensor_output__scan__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__lidar_sensor_output__scan__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__lidar_sensor_output__field_descriptors[1] =
{
  {
    "scans",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtobufMsgs__LidarSensorOutput, n_scans),
    offsetof(ProtobufMsgs__LidarSensorOutput, scans),
    &protobuf_msgs__lidar_sensor_output__scan__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__lidar_sensor_output__field_indices_by_name[] = {
  0,   /* field[0] = scans */
};
static const ProtobufCIntRange protobuf_msgs__lidar_sensor_output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protobuf_msgs__lidar_sensor_output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.LidarSensorOutput",
  "LidarSensorOutput",
  "ProtobufMsgs__LidarSensorOutput",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__LidarSensorOutput),
  1,
  protobuf_msgs__lidar_sensor_output__field_descriptors,
  protobuf_msgs__lidar_sensor_output__field_indices_by_name,
  1,  protobuf_msgs__lidar_sensor_output__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__lidar_sensor_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
