/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simulator/simulator.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "simulator/simulator.pb-c.h"
void   protobuf_msgs__simulator_image_output__init
                     (ProtobufMsgs__SimulatorImageOutput         *message)
{
  static const ProtobufMsgs__SimulatorImageOutput init_value = PROTOBUF_MSGS__SIMULATOR_IMAGE_OUTPUT__INIT;
  *message = init_value;
}
size_t protobuf_msgs__simulator_image_output__get_packed_size
                     (const ProtobufMsgs__SimulatorImageOutput *message)
{
  assert(message->base.descriptor == &protobuf_msgs__simulator_image_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__simulator_image_output__pack
                     (const ProtobufMsgs__SimulatorImageOutput *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__simulator_image_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__simulator_image_output__pack_to_buffer
                     (const ProtobufMsgs__SimulatorImageOutput *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__simulator_image_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__SimulatorImageOutput *
       protobuf_msgs__simulator_image_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__SimulatorImageOutput *)
     protobuf_c_message_unpack (&protobuf_msgs__simulator_image_output__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__simulator_image_output__free_unpacked
                     (ProtobufMsgs__SimulatorImageOutput *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__simulator_image_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protobuf_msgs__simulator_state__init
                     (ProtobufMsgs__SimulatorState         *message)
{
  static const ProtobufMsgs__SimulatorState init_value = PROTOBUF_MSGS__SIMULATOR_STATE__INIT;
  *message = init_value;
}
size_t protobuf_msgs__simulator_state__get_packed_size
                     (const ProtobufMsgs__SimulatorState *message)
{
  assert(message->base.descriptor == &protobuf_msgs__simulator_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__simulator_state__pack
                     (const ProtobufMsgs__SimulatorState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__simulator_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__simulator_state__pack_to_buffer
                     (const ProtobufMsgs__SimulatorState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__simulator_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__SimulatorState *
       protobuf_msgs__simulator_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__SimulatorState *)
     protobuf_c_message_unpack (&protobuf_msgs__simulator_state__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__simulator_state__free_unpacked
                     (ProtobufMsgs__SimulatorState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__simulator_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protobuf_msgs__simulator_image_output__field_descriptors[3] =
{
  {
    "width",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__SimulatorImageOutput, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__SimulatorImageOutput, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixels",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__SimulatorImageOutput, pixels),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__simulator_image_output__field_indices_by_name[] = {
  1,   /* field[1] = height */
  2,   /* field[2] = pixels */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange protobuf_msgs__simulator_image_output__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protobuf_msgs__simulator_image_output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.SimulatorImageOutput",
  "SimulatorImageOutput",
  "ProtobufMsgs__SimulatorImageOutput",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__SimulatorImageOutput),
  3,
  protobuf_msgs__simulator_image_output__field_descriptors,
  protobuf_msgs__simulator_image_output__field_indices_by_name,
  1,  protobuf_msgs__simulator_image_output__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__simulator_image_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__simulator_state__field_descriptors[5] =
{
  {
    "speed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__SimulatorState, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wheel_off_track",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ProtobufMsgs__SimulatorState, n_wheel_off_track),
    offsetof(ProtobufMsgs__SimulatorState, wheel_off_track),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__SimulatorState, image),
    &protobuf_msgs__simulator_image_output__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ProtobufMsgs__SimulatorState, n_pos),
    offsetof(ProtobufMsgs__SimulatorState, pos),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isDrifting",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__SimulatorState, isdrifting),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__simulator_state__field_indices_by_name[] = {
  2,   /* field[2] = image */
  4,   /* field[4] = isDrifting */
  3,   /* field[3] = pos */
  0,   /* field[0] = speed */
  1,   /* field[1] = wheel_off_track */
};
static const ProtobufCIntRange protobuf_msgs__simulator_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor protobuf_msgs__simulator_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.SimulatorState",
  "SimulatorState",
  "ProtobufMsgs__SimulatorState",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__SimulatorState),
  5,
  protobuf_msgs__simulator_state__field_descriptors,
  protobuf_msgs__simulator_state__field_indices_by_name,
  1,  protobuf_msgs__simulator_state__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__simulator_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue protobuf_msgs__sim_status__enum_values_by_number[3] =
{
  { "SIM_PAUSED", "PROTOBUF_MSGS__SIM_STATUS__SIM_PAUSED", 0 },
  { "SIM_REQ_STEP", "PROTOBUF_MSGS__SIM_STATUS__SIM_REQ_STEP", 1 },
  { "SIM_REQ_RESET", "PROTOBUF_MSGS__SIM_STATUS__SIM_REQ_RESET", 2 },
};
static const ProtobufCIntRange protobuf_msgs__sim_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex protobuf_msgs__sim_status__enum_values_by_name[3] =
{
  { "SIM_PAUSED", 0 },
  { "SIM_REQ_RESET", 2 },
  { "SIM_REQ_STEP", 1 },
};
const ProtobufCEnumDescriptor protobuf_msgs__sim_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "protobuf_msgs.SimStatus",
  "SimStatus",
  "ProtobufMsgs__SimStatus",
  "protobuf_msgs",
  3,
  protobuf_msgs__sim_status__enum_values_by_number,
  3,
  protobuf_msgs__sim_status__enum_values_by_name,
  1,
  protobuf_msgs__sim_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
