/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simulator/simulator.proto */

#ifndef PROTOBUF_C_simulator_2fsimulator_2eproto__INCLUDED
#define PROTOBUF_C_simulator_2fsimulator_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ProtobufMsgs__SimulatorImageOutput ProtobufMsgs__SimulatorImageOutput;
typedef struct _ProtobufMsgs__SimulatorState ProtobufMsgs__SimulatorState;


/* --- enums --- */

/*
 * Possible Sim Requests. Useful for interfaces with Gym
 */
typedef enum _ProtobufMsgs__SimStatus {
  /*
   * Simulator is paused 
   */
  PROTOBUF_MSGS__SIM_STATUS__SIM_PAUSED = 0,
  /*
   * Request single step 
   */
  PROTOBUF_MSGS__SIM_STATUS__SIM_REQ_STEP = 1,
  /*
   * Request hard reset 
   */
  PROTOBUF_MSGS__SIM_STATUS__SIM_REQ_RESET = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTOBUF_MSGS__SIM_STATUS)
} ProtobufMsgs__SimStatus;

/* --- messages --- */

/*
 * Simulator sensor outputs.
 */
struct  _ProtobufMsgs__SimulatorImageOutput
{
  ProtobufCMessage base;
  uint32_t width;
  uint32_t height;
  ProtobufCBinaryData pixels;
};
#define PROTOBUF_MSGS__SIMULATOR_IMAGE_OUTPUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__simulator_image_output__descriptor) \
    , 0, 0, {0,NULL} }


/*
 * Generic state of Simulator
 */
struct  _ProtobufMsgs__SimulatorState
{
  ProtobufCMessage base;
  /*
   * Meters per second 
   */
  float speed;
  /*
   * [0] = FL, [1] = FR, [2] = RL, [3] = RR 
   */
  size_t n_wheel_off_track;
  protobuf_c_boolean *wheel_off_track;
  /*
   * Image frame 
   */
  ProtobufMsgs__SimulatorImageOutput *image;
  /*
   * [0] = x, [1] = y, [2] = z 
   */
  size_t n_pos;
  float *pos;
  /*
   * =false when not drifting 
   */
  protobuf_c_boolean isdrifting;
};
#define PROTOBUF_MSGS__SIMULATOR_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__simulator_state__descriptor) \
    , 0, 0,NULL, NULL, 0,NULL, 0 }


/* ProtobufMsgs__SimulatorImageOutput methods */
void   protobuf_msgs__simulator_image_output__init
                     (ProtobufMsgs__SimulatorImageOutput         *message);
size_t protobuf_msgs__simulator_image_output__get_packed_size
                     (const ProtobufMsgs__SimulatorImageOutput   *message);
size_t protobuf_msgs__simulator_image_output__pack
                     (const ProtobufMsgs__SimulatorImageOutput   *message,
                      uint8_t             *out);
size_t protobuf_msgs__simulator_image_output__pack_to_buffer
                     (const ProtobufMsgs__SimulatorImageOutput   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__SimulatorImageOutput *
       protobuf_msgs__simulator_image_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__simulator_image_output__free_unpacked
                     (ProtobufMsgs__SimulatorImageOutput *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__SimulatorState methods */
void   protobuf_msgs__simulator_state__init
                     (ProtobufMsgs__SimulatorState         *message);
size_t protobuf_msgs__simulator_state__get_packed_size
                     (const ProtobufMsgs__SimulatorState   *message);
size_t protobuf_msgs__simulator_state__pack
                     (const ProtobufMsgs__SimulatorState   *message,
                      uint8_t             *out);
size_t protobuf_msgs__simulator_state__pack_to_buffer
                     (const ProtobufMsgs__SimulatorState   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__SimulatorState *
       protobuf_msgs__simulator_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__simulator_state__free_unpacked
                     (ProtobufMsgs__SimulatorState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtobufMsgs__SimulatorImageOutput_Closure)
                 (const ProtobufMsgs__SimulatorImageOutput *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__SimulatorState_Closure)
                 (const ProtobufMsgs__SimulatorState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    protobuf_msgs__sim_status__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__simulator_image_output__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__simulator_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_simulator_2fsimulator_2eproto__INCLUDED */
