/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/energy.proto */

#ifndef PROTOBUF_C_outputs_2fenergy_2eproto__INCLUDED
#define PROTOBUF_C_outputs_2fenergy_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ProtobufMsgs__EnergySensorOutput ProtobufMsgs__EnergySensorOutput;


/* --- enums --- */


/* --- messages --- */

struct  _ProtobufMsgs__EnergySensorOutput
{
  ProtobufCMessage base;
  /*
   * The measure supply voltage measured in volts (V).
   */
  float supplyvoltage;
  /*
   * The current amp draw in amperes (A) of the power supply source.
   */
  float currentamps;
  /*
   * The current power output of the Rover measured in watts (W).
   */
  float powerwatts;
};
#define PROTOBUF_MSGS__ENERGY_SENSOR_OUTPUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__energy_sensor_output__descriptor) \
    , 0, 0, 0 }


/* ProtobufMsgs__EnergySensorOutput methods */
void   protobuf_msgs__energy_sensor_output__init
                     (ProtobufMsgs__EnergySensorOutput         *message);
size_t protobuf_msgs__energy_sensor_output__get_packed_size
                     (const ProtobufMsgs__EnergySensorOutput   *message);
size_t protobuf_msgs__energy_sensor_output__pack
                     (const ProtobufMsgs__EnergySensorOutput   *message,
                      uint8_t             *out);
size_t protobuf_msgs__energy_sensor_output__pack_to_buffer
                     (const ProtobufMsgs__EnergySensorOutput   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__EnergySensorOutput *
       protobuf_msgs__energy_sensor_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__energy_sensor_output__free_unpacked
                     (ProtobufMsgs__EnergySensorOutput *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtobufMsgs__EnergySensorOutput_Closure)
                 (const ProtobufMsgs__EnergySensorOutput *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protobuf_msgs__energy_sensor_output__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_outputs_2fenergy_2eproto__INCLUDED */
