/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/generic.proto */

#ifndef PROTOBUF_C_outputs_2fgeneric_2eproto__INCLUDED
#define PROTOBUF_C_outputs_2fgeneric_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ProtobufMsgs__GenericIntScalar ProtobufMsgs__GenericIntScalar;
typedef struct _ProtobufMsgs__GenericFloatScalar ProtobufMsgs__GenericFloatScalar;
typedef struct _ProtobufMsgs__GenericBoolScalar ProtobufMsgs__GenericBoolScalar;
typedef struct _ProtobufMsgs__GenericStringScalar ProtobufMsgs__GenericStringScalar;
typedef struct _ProtobufMsgs__GenericIntArray ProtobufMsgs__GenericIntArray;
typedef struct _ProtobufMsgs__GenericFloatArray ProtobufMsgs__GenericFloatArray;
typedef struct _ProtobufMsgs__GenericBoolArray ProtobufMsgs__GenericBoolArray;
typedef struct _ProtobufMsgs__GenericStringArray ProtobufMsgs__GenericStringArray;


/* --- enums --- */


/* --- messages --- */

/*
 * This message holds a single integer value, it will be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericIntScalar
{
  ProtobufCMessage base;
  char *key;
  int32_t value;
};
#define PROTOBUF_MSGS__GENERIC_INT_SCALAR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_int_scalar__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/*
 * This message holds a single float value, it will be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericFloatScalar
{
  ProtobufCMessage base;
  char *key;
  float value;
};
#define PROTOBUF_MSGS__GENERIC_FLOAT_SCALAR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_float_scalar__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/*
 * This message holds a single boolean value, it will *NOT* be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericBoolScalar
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean value;
};
#define PROTOBUF_MSGS__GENERIC_BOOL_SCALAR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_bool_scalar__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/*
 * This message holds a single string value, it will *NOT* be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericStringScalar
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define PROTOBUF_MSGS__GENERIC_STRING_SCALAR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_string_scalar__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * This message holds an array of integer values, it will *NOT* be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericIntArray
{
  ProtobufCMessage base;
  char *key;
  size_t n_values;
  int32_t *values;
};
#define PROTOBUF_MSGS__GENERIC_INT_ARRAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_int_array__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


/*
 * This message holds an array of float values, it will *NOT* be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericFloatArray
{
  ProtobufCMessage base;
  char *key;
  size_t n_values;
  float *values;
};
#define PROTOBUF_MSGS__GENERIC_FLOAT_ARRAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_float_array__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


/*
 * This message holds an array of boolean values, it will *NOT* be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericBoolArray
{
  ProtobufCMessage base;
  char *key;
  size_t n_values;
  protobuf_c_boolean *values;
};
#define PROTOBUF_MSGS__GENERIC_BOOL_ARRAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_bool_array__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


/*
 * This message holds an array of string values, it will *NOT* be plotted in the debug view of roverctl
 */
struct  _ProtobufMsgs__GenericStringArray
{
  ProtobufCMessage base;
  char *key;
  size_t n_values;
  char **values;
};
#define PROTOBUF_MSGS__GENERIC_STRING_ARRAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__generic_string_array__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


/* ProtobufMsgs__GenericIntScalar methods */
void   protobuf_msgs__generic_int_scalar__init
                     (ProtobufMsgs__GenericIntScalar         *message);
size_t protobuf_msgs__generic_int_scalar__get_packed_size
                     (const ProtobufMsgs__GenericIntScalar   *message);
size_t protobuf_msgs__generic_int_scalar__pack
                     (const ProtobufMsgs__GenericIntScalar   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_int_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericIntScalar   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericIntScalar *
       protobuf_msgs__generic_int_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_int_scalar__free_unpacked
                     (ProtobufMsgs__GenericIntScalar *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__GenericFloatScalar methods */
void   protobuf_msgs__generic_float_scalar__init
                     (ProtobufMsgs__GenericFloatScalar         *message);
size_t protobuf_msgs__generic_float_scalar__get_packed_size
                     (const ProtobufMsgs__GenericFloatScalar   *message);
size_t protobuf_msgs__generic_float_scalar__pack
                     (const ProtobufMsgs__GenericFloatScalar   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_float_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericFloatScalar   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericFloatScalar *
       protobuf_msgs__generic_float_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_float_scalar__free_unpacked
                     (ProtobufMsgs__GenericFloatScalar *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__GenericBoolScalar methods */
void   protobuf_msgs__generic_bool_scalar__init
                     (ProtobufMsgs__GenericBoolScalar         *message);
size_t protobuf_msgs__generic_bool_scalar__get_packed_size
                     (const ProtobufMsgs__GenericBoolScalar   *message);
size_t protobuf_msgs__generic_bool_scalar__pack
                     (const ProtobufMsgs__GenericBoolScalar   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_bool_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericBoolScalar   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericBoolScalar *
       protobuf_msgs__generic_bool_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_bool_scalar__free_unpacked
                     (ProtobufMsgs__GenericBoolScalar *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__GenericStringScalar methods */
void   protobuf_msgs__generic_string_scalar__init
                     (ProtobufMsgs__GenericStringScalar         *message);
size_t protobuf_msgs__generic_string_scalar__get_packed_size
                     (const ProtobufMsgs__GenericStringScalar   *message);
size_t protobuf_msgs__generic_string_scalar__pack
                     (const ProtobufMsgs__GenericStringScalar   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_string_scalar__pack_to_buffer
                     (const ProtobufMsgs__GenericStringScalar   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericStringScalar *
       protobuf_msgs__generic_string_scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_string_scalar__free_unpacked
                     (ProtobufMsgs__GenericStringScalar *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__GenericIntArray methods */
void   protobuf_msgs__generic_int_array__init
                     (ProtobufMsgs__GenericIntArray         *message);
size_t protobuf_msgs__generic_int_array__get_packed_size
                     (const ProtobufMsgs__GenericIntArray   *message);
size_t protobuf_msgs__generic_int_array__pack
                     (const ProtobufMsgs__GenericIntArray   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_int_array__pack_to_buffer
                     (const ProtobufMsgs__GenericIntArray   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericIntArray *
       protobuf_msgs__generic_int_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_int_array__free_unpacked
                     (ProtobufMsgs__GenericIntArray *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__GenericFloatArray methods */
void   protobuf_msgs__generic_float_array__init
                     (ProtobufMsgs__GenericFloatArray         *message);
size_t protobuf_msgs__generic_float_array__get_packed_size
                     (const ProtobufMsgs__GenericFloatArray   *message);
size_t protobuf_msgs__generic_float_array__pack
                     (const ProtobufMsgs__GenericFloatArray   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_float_array__pack_to_buffer
                     (const ProtobufMsgs__GenericFloatArray   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericFloatArray *
       protobuf_msgs__generic_float_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_float_array__free_unpacked
                     (ProtobufMsgs__GenericFloatArray *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__GenericBoolArray methods */
void   protobuf_msgs__generic_bool_array__init
                     (ProtobufMsgs__GenericBoolArray         *message);
size_t protobuf_msgs__generic_bool_array__get_packed_size
                     (const ProtobufMsgs__GenericBoolArray   *message);
size_t protobuf_msgs__generic_bool_array__pack
                     (const ProtobufMsgs__GenericBoolArray   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_bool_array__pack_to_buffer
                     (const ProtobufMsgs__GenericBoolArray   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericBoolArray *
       protobuf_msgs__generic_bool_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_bool_array__free_unpacked
                     (ProtobufMsgs__GenericBoolArray *message,
                      ProtobufCAllocator *allocator);
/* ProtobufMsgs__GenericStringArray methods */
void   protobuf_msgs__generic_string_array__init
                     (ProtobufMsgs__GenericStringArray         *message);
size_t protobuf_msgs__generic_string_array__get_packed_size
                     (const ProtobufMsgs__GenericStringArray   *message);
size_t protobuf_msgs__generic_string_array__pack
                     (const ProtobufMsgs__GenericStringArray   *message,
                      uint8_t             *out);
size_t protobuf_msgs__generic_string_array__pack_to_buffer
                     (const ProtobufMsgs__GenericStringArray   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__GenericStringArray *
       protobuf_msgs__generic_string_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__generic_string_array__free_unpacked
                     (ProtobufMsgs__GenericStringArray *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtobufMsgs__GenericIntScalar_Closure)
                 (const ProtobufMsgs__GenericIntScalar *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__GenericFloatScalar_Closure)
                 (const ProtobufMsgs__GenericFloatScalar *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__GenericBoolScalar_Closure)
                 (const ProtobufMsgs__GenericBoolScalar *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__GenericStringScalar_Closure)
                 (const ProtobufMsgs__GenericStringScalar *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__GenericIntArray_Closure)
                 (const ProtobufMsgs__GenericIntArray *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__GenericFloatArray_Closure)
                 (const ProtobufMsgs__GenericFloatArray *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__GenericBoolArray_Closure)
                 (const ProtobufMsgs__GenericBoolArray *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__GenericStringArray_Closure)
                 (const ProtobufMsgs__GenericStringArray *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protobuf_msgs__generic_int_scalar__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__generic_float_scalar__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__generic_bool_scalar__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__generic_string_scalar__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__generic_int_array__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__generic_float_array__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__generic_bool_array__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__generic_string_array__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_outputs_2fgeneric_2eproto__INCLUDED */
