/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/lidar.proto */

#ifndef PROTOBUF_C_outputs_2flidar_2eproto__INCLUDED
#define PROTOBUF_C_outputs_2flidar_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ProtobufMsgs__LidarSensorOutput ProtobufMsgs__LidarSensorOutput;
typedef struct _ProtobufMsgs__LidarSensorOutput__Scan ProtobufMsgs__LidarSensorOutput__Scan;


/* --- enums --- */


/* --- messages --- */

/*
 * A scan corresponds to a single shot of the laser. One rotation contains many scans.
 */
struct  _ProtobufMsgs__LidarSensorOutput__Scan
{
  ProtobufCMessage base;
  /*
   * angle in degrees
   */
  float angle;
  /*
   * distance in meters
   */
  float distance;
  /*
   * quality of the scan (0 is worst, 255 is best)
   */
  uint32_t quality;
  /*
   * true if this is the start of a new scan rotation
   */
  protobuf_c_boolean isstart;
};
#define PROTOBUF_MSGS__LIDAR_SENSOR_OUTPUT__SCAN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__lidar_sensor_output__scan__descriptor) \
    , 0, 0, 0, 0 }


struct  _ProtobufMsgs__LidarSensorOutput
{
  ProtobufCMessage base;
  /*
   * Many (but not necessarily all) scans in a single rotation
   */
  size_t n_scans;
  ProtobufMsgs__LidarSensorOutput__Scan **scans;
};
#define PROTOBUF_MSGS__LIDAR_SENSOR_OUTPUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__lidar_sensor_output__descriptor) \
    , 0,NULL }


/* ProtobufMsgs__LidarSensorOutput__Scan methods */
void   protobuf_msgs__lidar_sensor_output__scan__init
                     (ProtobufMsgs__LidarSensorOutput__Scan         *message);
/* ProtobufMsgs__LidarSensorOutput methods */
void   protobuf_msgs__lidar_sensor_output__init
                     (ProtobufMsgs__LidarSensorOutput         *message);
size_t protobuf_msgs__lidar_sensor_output__get_packed_size
                     (const ProtobufMsgs__LidarSensorOutput   *message);
size_t protobuf_msgs__lidar_sensor_output__pack
                     (const ProtobufMsgs__LidarSensorOutput   *message,
                      uint8_t             *out);
size_t protobuf_msgs__lidar_sensor_output__pack_to_buffer
                     (const ProtobufMsgs__LidarSensorOutput   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__LidarSensorOutput *
       protobuf_msgs__lidar_sensor_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__lidar_sensor_output__free_unpacked
                     (ProtobufMsgs__LidarSensorOutput *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtobufMsgs__LidarSensorOutput__Scan_Closure)
                 (const ProtobufMsgs__LidarSensorOutput__Scan *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__LidarSensorOutput_Closure)
                 (const ProtobufMsgs__LidarSensorOutput *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protobuf_msgs__lidar_sensor_output__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__lidar_sensor_output__scan__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_outputs_2flidar_2eproto__INCLUDED */
